### DISCUSSION TITLE
서브모듈인 레포B를 수정하면 레포A에도 자동으로 업데이트되는 깃허브 액션

### DISCUSSION THREAD

**Discussion by Jinsun-Lee** [Jinsun-Lee/devops-template#16] [Github]
### 모노레포
단일 리포지터리에 여러 개의 서브 프로젝트가 존재
![image](https://github.com/user-attachments/assets/40a182e7-1937-4a16-af5e-c68b6d3375ee)

모놀리스(Monolith)
`하나의 서비스를 하나의 프로젝트로 만들고 하나의 리포지토리로 관리`
소스 코드를 모듈화하지 않고 하나의 리포지터리에 모두 저장
단일 버전이라 코드 재사용 용이, 빌드 및 배포 단순
but 분리가 어렵고 기능 추가나 삭제가 레포 전체에 영향

멀티레포(Multi Repo)
`하나의 서비스를 여러 프로젝트로 나누고 여러 리포지토리로 관리`
소스 코드를 모듈화한 뒤 각 모듈에 독자적인 영역을 부여
버전관리를 통해 기능 변경이 다른 레포에 영향을 끼치지 않음
but 서로 독립되어 있어 코드의 재사용과 빌드 및 배포가 복잡

모노레포(Monorepo)
`하나의 서비스를 여러 프로젝트로 나누고 하나의 리포지토리로 관리`
하나의 레포 안에, 하나의 커밋 히스토리 = 개발 흐름 파악 용이
여러곳에서 코드를 공유하고 재사용 용이

**Comment by Jinsun-Lee** [comment]
1. 레포A를 클론
2. 레포A로 이동
3. 레포B를 클론
아래 명령 실행하면 레포A 안에 레포B가 생성됨
```
git submodule add https://github.com/Jinsun-Lee/github_test_B.git
```
<br>

레포A에서 푸쉬하면 깃허브에 이렇게 모듈이 연결됨
![image](https://github.com/user-attachments/assets/3f2e7542-393e-4bc0-8638-a8a01fac0122)

<br>

참고로 레포A에만 파일이 생성됨, 레포B에는 별도의 파일이 생성되지 않음
레포A의 `.gitmodules` 파일 
```
[submodule "github_test_B"]
	path = github_test_B
	url = https://github.com/Jinsun-Lee/github_test_B.git
```

---

<br>

### +) 다른 경로 + 다른 이름으로 연결하고 싶을 경우
<details>
<summary>내용 보기</summary>

<br>

 coding_test 레포 안에 + (다른경로) FIXED 폴더 안에 + (다른이름) CT_samsung 레포를 samsung으로 연결
![Image](https://github.com/user-attachments/assets/7237e699-2a00-4286-80a4-aa5508976662)

<br>

- coding_test가 레포A, CT_samsung가 레포B(서브모듈)
- coding_test/FIXED/CT_samsung → coding_test//samsung 이렇게 연결됨
- FIXED 폴더 안에 +  원래 레포 이름인 CT_samsung 대신 samsung으로 연결(--name를 써서 내부적으로는 CT_samsung로 연결)
```
cd Desktop/coding_test
git submodule add --name CT_samsung https://github.com/Jinsun-Lee/CT_samsung.git FIXED/samsung
```

<br>

이렇게 파일 생김(리드미를 push하라고 하면 잘못된 것)
![image](https://github.com/user-attachments/assets/75143422-86b5-4668-a42e-6cf49f278f95)

<br>

.gitmodules 파일
```
[submodule "CT_samsung"]
	path = FIXED/samsung
	url = https://github.com/Jinsun-Lee/CT_samsung.git
```

<br>

웹에서는 이렇게 제대로 잘 보임
![image](https://github.com/user-attachments/assets/0430b6f5-01a2-40ef-b266-880fc648f79c)

</details>


<br>

**Comment by Jinsun-Lee** [comment]
하위 레포 수정 후, 반영하지 않으면 상위 레포에 반영되지 않음  
이에 서브모듈인 레포B를 수정하면 레포A에도 자동으로 업데이트되도록 깃허브 액션 생성

<br>

## 1. 레포A에서 작업 권한 설정
![image](https://github.com/user-attachments/assets/190829f9-eebf-465f-8c31-7bcc30b5a67a)
쭉 내려서 아래처럼 설정... 보면 이해할 수 있어서 적당히 선택하면 됨
<br>

![image](https://github.com/user-attachments/assets/b7dfe292-33d5-4f1a-bb23-4aa9d89c6285)

<br><br>

## 2. 레포B에 Secretes and variables 추가
```
LOGIN_TOKEN
```
토큰은 발급 받아서 각자 쓰기 ㄱㄱ 
[이건 내 토큰 내가 보려고 쓰는 것 비공개 레포임](https://github.com/Jinsun-Lee/Github-template)

<br><br>

## 3. 레포B에 파일 생성
파일명
```
.github/workflows/update-repoA.yml
```
파일내용
```
name: github_test_A의 서브모듈 포인터 자동 업데이트

on:
  push:
    branches:
      - master  # github_test_B에서 master 브랜치 푸시될 때 실행

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    env:
      GIT_USERNAME: "Jinsun-Lee"
      GIT_EMAIL: "012vision@gmail.com"
      GITHUB_ID: "Jinsun-Lee"      
      
      REPO_A: "github_test_A"                  # 메인 레포 (서브모듈 포함)
      REPO_B: "github_test_B"                  # 서브모듈 레포
      BRANCH: "master"                         # 사용할 브랜치
      SUBMODULE_PATH: "github_test_B"          # 레포A 내부에서의 서브모듈 위치

    steps:
      - name: github_test_A 클론 + 서브모듈 포함 체크아웃
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_ID }}/${{ env.REPO_A }}
          token: ${{ secrets.LOGIN_TOKEN }}
          submodules: 'recursive'
          ref: ${{ env.BRANCH }}

      - name: Git 사용자 정보 설정
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: 서브모듈 URL 인증 토큰 포함으로 변경
        run: |
          git config -f .gitmodules submodule.${{ env.SUBMODULE_PATH }}.url https://x-access-token:${{ secrets.LOGIN_TOKEN }}@github.com/${{ env.GITHUB_ID }}/${{ env.REPO_B }}.git
          git submodule sync

      - name: 서브모듈 최신 커밋으로 업데이트
        run: |
          git submodule update --remote --checkout
          git add $SUBMODULE_PATH
          COMMIT_MSG=$(cd $SUBMODULE_PATH && git log -1 --pretty=%B)
          git commit -m "[모듈업뎃] $COMMIT_MSG" || echo "변경 없음"
          git push origin $BRANCH
```

위 파일에서 아래 내용을 적절히 수정하면 됨
다른 사람이 쓸 경우에는 사용자 정보도 수정 필요
```
env:
      GIT_USERNAME: "Jinsun-Lee"
      GIT_EMAIL: "012vision@gmail.com"
      GITHUB_ID: "Jinsun-Lee"      
      
      REPO_A: "github_test_A"                  # 메인 레포 (서브모듈 포함)
      REPO_B: "github_test_B"                  # 서브모듈 레포
      BRANCH: "master"                         # 사용할 브랜치
      SUBMODULE_PATH: "github_test_B"          # 레포A 내부에서의 서브모듈 위치
```
커밋 메시지를 나는 기존의 커밋을 유지하게 하고  
앞에 [모듈업뎃]을 추가했는데 아래처럼 쓰면 레포A에 레포B의 원래 커밋이 그래도 반영된다
```
git commit -m "$COMMIT_MSG" || echo "변경 없음"
```

<br><br>

## 4. 결과
서브모듈에 해당하는 레포B에서 내용을 변경  
![image](https://github.com/user-attachments/assets/5b8e1696-e863-4f3c-a63c-02901880f2da)
<br>

레포B에서 Action이 동작하는 것 확인  
![image](https://github.com/user-attachments/assets/8c99bc0b-ebcb-4c21-bcee-6fa026c78aab)
<br>

레포A를 확인해 보면 잘 반영되어 있음  
![image](https://github.com/user-attachments/assets/37c38ab4-e874-49e1-840e-8816460ebf2f)
